---

- hosts: all
  become: true

  tasks:
  - name: remove apache
    apt:
      name: apache2
      state: absent
  - name: update pkg
    apt:
      update_cache: yes
  - name: remove php for support of apache2
    apt:
      name: libapache2-mod-php
      state: absent
